Repository Kusithm-HDmedi-Team-C/Backend, pull requests merged in 2023-09, with the labels that each got.

#2 Feature/1 setting
  src/main/java/com/example/kusithms_hdmedi_project/domain/sample/controller/SampleController.java
  src/main/java/com/example/kusithms_hdmedi_project/domain/sample/dto/request/SampleRequestDto.java
  src/main/java/com/example/kusithms_hdmedi_project/domain/sample/dto/response/SampleResponseDto.java
  src/main/java/com/example/kusithms_hdmedi_project/domain/sample/entity/Sample.java
  src/main/java/com/example/kusithms_hdmedi_project/domain/sample/repository/SampleRepository.java
  src/main/java/com/example/kusithms_hdmedi_project/domain/sample/service/SampleService.java
  src/main/java/com/example/kusithms_hdmedi_project/global/common/BaseResponse.java
  src/main/java/com/example/kusithms_hdmedi_project/global/common/BaseTimeEntity.java
  src/main/java/com/example/kusithms_hdmedi_project/global/common/HealthCheckApiController.java
  src/main/java/com/example/kusithms_hdmedi_project/global/common/SuccessCode.java
  src/main/java/com/example/kusithms_hdmedi_project/global/config/JpaConfig.java
  src/main/java/com/example/kusithms_hdmedi_project/global/error/dto/ErrorBaseResponse.java
  src/main/java/com/example/kusithms_hdmedi_project/global/error/exception/BusinessException.java
  src/main/java/com/example/kusithms_hdmedi_project/global/error/exception/ConflictException.java
  src/main/java/com/example/kusithms_hdmedi_project/global/error/exception/ErrorCode.java
  src/main/java/com/example/kusithms_hdmedi_project/global/error/handler/GlobalExceptionHandler.java
Labels: feat, 진영🐧

#10 Feature/3 nonstop deploy
  .github/workflows/cicd.yml
  Dockerfile
  docker-compose.yml
  scripts/deploy.sh
  src/main/java/com/example/kusithms_hdmedi_project/global/common/HealthCheckApiController.java
Labels: feat, 진영🐧

#12 Feature/11 survey
  src/main/java/com/example/kusithms_hdmedi_project/global/common/BaseTimeEntity.java
  src/main/java/com/example/kusithms_hdmedi_project/question/entity/Example.java
  src/main/java/com/example/kusithms_hdmedi_project/question/entity/QuestionType.java
  src/main/java/com/example/kusithms_hdmedi_project/question/entity/SurveyQuestion.java
Labels: feat, 희엽🦈

#15 Feature/13 survey
  src/main/java/com/example/kusithms_hdmedi_project/question/controller/SurveyQuestionController.java
  src/main/java/com/example/kusithms_hdmedi_project/question/dto/Response/ExampleResponseDto.java
  src/main/java/com/example/kusithms_hdmedi_project/question/dto/Response/SurveyQuestionResponseDto.java
  src/main/java/com/example/kusithms_hdmedi_project/question/entity/Example.java
  src/main/java/com/example/kusithms_hdmedi_project/question/entity/SurveyQuestion.java
  src/main/java/com/example/kusithms_hdmedi_project/question/repository/SurveyQuestionRepository.java
  src/main/java/com/example/kusithms_hdmedi_project/question/service/SurveyQuestionService.java
  src/test/java/com/example/kusithms_hdmedi_project/question/repository/SurveyQuestionRepositoryTest.java
Labels: feat, 희엽🦈

#18 Feature/16 survey result
  src/main/java/com/example/kusithms_hdmedi_project/question/controller/SurveyResultController.java
  src/main/java/com/example/kusithms_hdmedi_project/question/dto/Request/SurveyResultRequestDto.java
  src/main/java/com/example/kusithms_hdmedi_project/question/dto/Request/TotalSurveyResultRequestDto.java
  src/main/java/com/example/kusithms_hdmedi_project/question/dto/Response/SurveyResultResponseDto.java
  src/main/java/com/example/kusithms_hdmedi_project/question/service/SurveyResultService.java
Labels: feat, 진영🐧

#23 Feature/21 review domain
  src/main/java/com/example/kusithms_hdmedi_project/domain/review/controller/ReviewController.java
  src/main/java/com/example/kusithms_hdmedi_project/domain/review/entity/ExaminationType.java
  src/main/java/com/example/kusithms_hdmedi_project/domain/review/entity/Review.java
  src/main/java/com/example/kusithms_hdmedi_project/domain/review/entity/ReviewExamination.java
  src/main/java/com/example/kusithms_hdmedi_project/domain/review/entity/VerifiedReview.java
  src/main/java/com/example/kusithms_hdmedi_project/domain/review/repository/ReviewRepository.java
  src/main/java/com/example/kusithms_hdmedi_project/domain/review/repository/VReviewRepository.java
  src/main/java/com/example/kusithms_hdmedi_project/domain/review/service/ReviewService.java
Labels: feat, 진영🐧

#26 Feature/25 hospital
  src/main/java/com/example/kusithms_hdmedi_project/domain/hospital/entity/Hospital.java
  src/main/java/com/example/kusithms_hdmedi_project/domain/hospital/repository/HospitalRepository.java
  src/main/java/com/example/kusithms_hdmedi_project/domain/hospital/service/HospitalService.java
  src/test/java/com/example/kusithms_hdmedi_project/domain/hospital/repository/HospitalRepositoryTest.java
Labels: feat, 희엽🦈

#28 [fix] #27 hospital entity review -> verifiedReivew
  src/main/java/com/example/kusithms_hdmedi_project/domain/hospital/entity/Hospital.java
Labels: fix, 진영🐧

#30 29 s3
  build.gradle
  src/main/java/com/example/kusithms_hdmedi_project/global/infra/S3Config.java
  src/main/java/com/example/kusithms_hdmedi_project/global/infra/S3Service.java
Labels: feat, 진영🐧

#32 Feature/24 review api
  src/main/java/com/example/kusithms_hdmedi_project/domain/review/controller/ReviewController.java
  src/main/java/com/example/kusithms_hdmedi_project/domain/review/dto/request/CreateReviewRequestDto.java
  src/main/java/com/example/kusithms_hdmedi_project/domain/review/dto/response/CreateReviewResponseDto.java
  src/main/java/com/example/kusithms_hdmedi_project/domain/review/dto/response/GetHospitalVReviewResponseDto.java
  src/main/java/com/example/kusithms_hdmedi_project/domain/review/dto/response/VerifyReviewResponseDto.java
  src/main/java/com/example/kusithms_hdmedi_project/domain/review/entity/ExaminationType.java
  src/main/java/com/example/kusithms_hdmedi_project/domain/review/entity/Review.java
  src/main/java/com/example/kusithms_hdmedi_project/domain/review/entity/ReviewExamination.java
  src/main/java/com/example/kusithms_hdmedi_project/domain/review/entity/VerifiedReview.java
  src/main/java/com/example/kusithms_hdmedi_project/domain/review/repository/ReviewExaminationRepository.java
  src/main/java/com/example/kusithms_hdmedi_project/domain/review/repository/VerifiedReviewRepository.java
  src/main/java/com/example/kusithms_hdmedi_project/domain/review/service/ReviewService.java
  src/main/java/com/example/kusithms_hdmedi_project/global/error/exception/EntityNotFoundException.java
  src/test/java/com/example/kusithms_hdmedi_project/domain/review/repository/ReviewRepositoryTest.java
Labels: feat, 진영🐧

#36 Feature/34 vreview repository method
  src/main/java/com/example/kusithms_hdmedi_project/domain/review/repository/VerifiedReviewRepository.java
  src/test/java/com/example/kusithms_hdmedi_project/domain/review/repository/ReviewRepositoryTest.java
Labels: feat, 진영🐧

#37 Feature/35 hospital reviewnum rating update
  src/main/java/com/example/kusithms_hdmedi_project/domain/hospital/entity/Hospital.java
  src/main/java/com/example/kusithms_hdmedi_project/domain/review/entity/VerifiedReview.java
  src/test/java/com/example/kusithms_hdmedi_project/domain/review/repository/ReviewRepositoryTest.java
Labels: feat, 진영🐧

#45 [fix] #44 존재하지 않는 Hospital 조회시 예외 발생
  build.gradle
  src/main/java/com/example/kusithms_hdmedi_project/domain/hospital/dto/response/HospitalDto.java
  src/main/java/com/example/kusithms_hdmedi_project/domain/hospital/entity/Hospital.java
  src/main/java/com/example/kusithms_hdmedi_project/domain/hospital/service/HospitalService.java
Labels: fix, 희엽🦈

#49 [fix] #48 병원 상세 조회 request parameter 명 변경
  src/main/java/com/example/kusithms_hdmedi_project/domain/hospital/controller/HospitalController.java
Labels: fix, 희엽🦈

#51 [fix] #50 조회문을 줄이기 위해 SurveyQuestion 엔티티의 examples 에 배치 사이즈 적용
  src/main/java/com/example/kusithms_hdmedi_project/domain/survey/entity/SurveyQuestion.java
Labels: fix, 희엽🦈

#58 [fix] #57 병원 조회 기준 변경
  src/main/java/com/example/kusithms_hdmedi_project/domain/hospital/service/HospitalService.java
Labels: fix, 희엽🦈
